services:
  unirepo:
    image: unirepo
    container_name: unirepo
    volumes:
    - ~/unirepo/repos:/repos
    - ~/unirepo/files:/files
    networks:
    - unirepo
    ports:
    - 8080:8080
    - 8081:8081
    command: ["-l","${LOGLEVEL:-info}"]
networks:
  unirepo:
    driver: bridge