services:
  unirepo:
    image: unirepo
    network_mode: host
    container_name: unirepo
    volumes:
    - ~/unirepo/repos:/repos
    - ~/unirepo/files:/files
    environment:
      LOGLEVEL: "${LOGLEVEL:-info}"
      HOST: "${HOSTNAME:-localhost}"
      RUN_DOCKER: "${RUN_DOCKER:-1}"